### ISSUE TITLE
Ability to import quotes from a old-quote format file.

### ISSUE THREAD

**Issue by wqyeo** [crazycarl/CarlBot9000#13]
A module to import quotes from the old-version of the quote format file.

**Comment by wqyeo** [comment]
A sample of how the old-quote format looks like: https://gist.github.com/Kaynn-Cahya/8fe0038386009788a955b8ea94122b8c

**Comment by IamTheCarl** [comment]
I mentioned this on Discord but I'm mentioning it here too for anyone who's coming across this out of context.

This "old format" is actually the format that RoboNitori exported quotes in. I just supported importing them. Carl Bot never exported a file like this.

**Comment by wqyeo** [comment]
#15
