### ISSUE TITLE
Features to add to quotes module

### ISSUE THREAD

**Issue by IamTheCarl** [crazycarl/CarlBot9000#2]
- [x] Random quote command.

- [x] Change owner of quote command.

- [x] Ability to export quote list.

- [x] Ability to import quote list.

- [x] Ability to change quote key

- [x] Ability to show the list of quotes

**Comment by IamTheCarl** [comment]
- Ability to change quote key

**Comment by wqyeo** [comment]
Added ability to export/import quotes;

This feature is now in the Beta Branch. #12
