### ISSUE TITLE
New Schedule Module

### ISSUE THREAD

**Issue by IamTheCarl** [crazycarl/CarlBot9000#4]
Enables the bot to setup events to be called at regular intervals or after a specified amount of time.
This will be used to implement automated backup systems and support a commands.

On the back end:

- [x] Set function to be called after specified amount of time, or at a specific datetime.
Note that these function events will not be saved for persistence between Carl Bot restarts.

On the front end:
- [x]  A command to set Carl Bot to issue a specific command after an interval of time.
This can be used to regularly broadcast messages, regularly record stats, to lock down a channel after a deadline, etc.

**Comment by Kaynn-Cahya** [comment]
Just added dis enhancement in `testPl0x` branch, as the branch name suggests, please test it before merging it into main pl0x.

Command: $>schedule <time> [message]`, where `time` is in seconds and `message` is optional

> Might need to do an implementation where is accepts specific date-time, hours, etc.

### Code Structure as follows:
`schedule.py` contains a class `Schedule` which represents an instance of a user's schedule.
`schedules_manager.py` contains a list of those schedules, and contains functions to manipulate them.

> **NOTE:** Both of these mentioned above are created in a new folder called `BotUtil`. Feel free to move them to the feels-correct directory if needed.

`scheduler.py` will then be the one handling the user's command, aka it is added into `carlbot.py` as a command.
`carlbot.py` now has a `schedule_timeout` function, it is used and called by the `Schedule` instance when it's instance timer has passed.

### Code Flow-structure:

1. At start, `scheduler.py` will load its function as a command into `carlbot.py`
2. When the user do `$>schedule <time> [message]`, it calls the function (obviously)
3. The function then does input validity checking, then calls the `new_schedule` function in `schedules_manager.py` with the respective inputs.
4. The `new_schedule` function then creates a new instance of `Schedule` class using the respective inputs and store it in its list.
5. The nue `Schedule` then construct itself, storing the message and userID. It will then create a new `threading.Timer` instance with the given time input.
6. When the `Timer` interval in the instance of the `Schedule` has passed, it will then call `schedule_timeout` function (with respective inputs) in `carlbot.py`, then `dispose_schedule` function in `schedules_manager.py`
7. `schedule_timeout` would then use the userID from the inputs to find and send a message to the related user using the message (or a Honk Honk text if none was set).
8. `dispose_schedule` removes `Schedule` from its list, effectively destroying all references to the Schedule instance. (To let the compiler do garbage collection on it)

**Comment by wqyeo** [comment]
Completed the schedule command, its now on the beta branch
