### ISSUE TITLE
Quotes can ping everyone.

### ISSUE THREAD

**Issue by IamTheCarl** [crazycarl/CarlBot9000#5]
Yep, if there's an @everyone ping in there, it'll work. That needs fixing.

**Comment by wqyeo** [comment]
A (temporary?) fix is done on the beta branch.
It checks if a given qoute contains @everyone, it it does it wraps every instance of @everyone in that in code-format like this: `@everyone`

Unless you want another kind of fix.

**Comment by IamTheCarl** [comment]
This bug still applies to the Java version of the bot. I think your proposed fix should still be able to fix this.

**Comment by IamTheCarl** [comment]
Your recommended fix worked.

**Comment by wqyeo** [comment]
When u finally fix the a bug after 1 year 
🤔
